version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80" # Map port 8000 on your machine to port 80 in the container
    volumes:
      - ./tasks.txt:/var/www/html/tasks.txt # Sync the tasks.txt file
    restart: always